"use client"
import { useRouter } from "next/navigation"
import { useState } from "react"
import { Loader2, Plus } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

export function LeadCreateForm(){const router=useRouter();const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function submit(fd:FormData){setBusy(true);setError("");const r=await fetch("/api/representative/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(fd.entries()))});const data=await r.json();setBusy(false);if(!r.ok)return setError(data.error||"Falha");setOpen(false);router.refresh()}return <>{!open?<Button onClick={()=>setOpen(true)}><Plus/>Novo lead</Button>:<div className="rounded-xl border bg-white p-5 shadow-sm"><div className="mb-4 flex justify-between"><strong>Novo lead</strong><Button variant="ghost" size="sm" onClick={()=>setOpen(false)}>Cancelar</Button></div><form action={submit} className="grid gap-3 sm:grid-cols-2"><div className="grid gap-2"><Label>Empresa / fazenda</Label><Input name="companyName" required/></div><div className="grid gap-2"><Label>Contato</Label><Input name="contactName" required/></div><div className="grid gap-2"><Label>Telefone</Label><Input name="phone" required/></div><div className="grid gap-2"><Label>E-mail</Label><Input name="email" type="email"/></div><div className="grid gap-2"><Label>Cidade</Label><Input name="city" required/></div><div className="grid gap-2"><Label>UF</Label><Input name="state" maxLength={2} required/></div><div className="grid gap-2"><Label>Origem</Label><Input name="source" placeholder="Indicação, feira, site..."/></div><div className="grid gap-2"><Label>Potencial (R$)</Label><Input name="valueEstimate" type="number" min="0" step="0.01"/></div>{error&&<p className="text-sm text-destructive sm:col-span-2">{error}</p>}<Button disabled={busy} className="sm:col-span-2">{busy&&<Loader2 className="animate-spin"/>}Cadastrar lead</Button></form></div>}</>}
