export const statusLabels: Record<string, string> = {
  REQUESTED: "Solicitado",
  IN_ANALYSIS: "Em análise",
  SENT: "Enviado",
  APPROVED: "Aprovado",
  REJECTED: "Recusado",
  EXPIRED: "Expirado",
  CONVERTED: "Convertido",
  PENDING: "Pendente",
  CONFIRMED: "Confirmado",
  IN_PRODUCTION: "Em produção",
  READY_TO_SHIP: "Pronto para expedição",
  SHIPPED: "Enviado",
  DELIVERED: "Entregue",
  CANCELLED: "Cancelado",
  NEW: "Novo",
  CONTACTED: "Contatado",
  QUALIFIED: "Qualificado",
  PROPOSAL: "Proposta",
  WON: "Ganho",
  LOST: "Perdido",
  FORECAST: "Prevista",
  PAID: "Paga",
  ACTIVE: "Ativo",
  BLOCKED: "Bloqueado",
  INACTIVE: "Inativo",
  PROSPECT: "Prospect",
  DRAFT: "Rascunho",
}
