import Link from "next/link"
import { notFound } from "next/navigation"
import { ArrowLeft, CheckCircle2, Clock3, Download, FileText, PackageCheck, ShieldCheck } from "lucide-react"
import { SiteHeader } from "@/components/site-header"
import { SiteFooter } from "@/components/site-footer"
import { ProductVisual } from "@/components/product-visual"
import { QuoteForm } from "@/components/quote-form"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Separator } from "@/components/ui/separator"
import { prisma } from "@/lib/prisma"

export const dynamic = "force-dynamic"


function rows(value: unknown) { return value && typeof value === "object" && !Array.isArray(value) ? Object.entries(value as Record<string, unknown>) : [] }

export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const product = await prisma.product.findUnique({ where: { slug }, include: { category: true, documents: { where: { isPublic: true } } } })
  if (!product || product.status !== "ACTIVE") notFound()
  const specs = rows(product.techSpecs), dimensions = rows(product.dimensions)
  return <><SiteHeader/><main className="container-wide py-8"><Button asChild variant="ghost" className="mb-5 -ml-3"><Link href="/catalogo"><ArrowLeft/>Voltar ao catálogo</Link></Button><div className="grid gap-10 lg:grid-cols-[1.05fr_.95fr]"><ProductVisual name={product.name} sku={product.sku} imageSrc={product.heroImage} priority className="min-h-[420px] border-sky-200 lg:min-h-[560px]"/><div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-primary">{product.category.name}</p><h1 className="font-display mt-2 text-3xl font-black tracking-tight text-slate-950 sm:text-4xl">{product.name}</h1><div className="brand-rule-sky mt-4"/><p className="mt-5 text-lg leading-8 text-slate-600">{product.shortDescription}</p><div className="mt-6 grid grid-cols-3 gap-3"><div className="border border-sky-200 bg-white p-4"><PackageCheck className="size-5 text-primary"/><p className="mt-3 text-xs text-muted-foreground">Disponibilidade</p><p className="text-sm font-bold">{product.stockStatus}</p></div><div className="border border-sky-200 bg-white p-4"><Clock3 className="size-5 text-primary"/><p className="mt-3 text-xs text-muted-foreground">Prazo estimado</p><p className="text-sm font-bold">{product.leadTimeDays ? `${product.leadTimeDays} dias` : "Consulte"}</p></div><div className="border border-sky-200 bg-white p-4"><ShieldCheck className="size-5 text-primary"/><p className="mt-3 text-xs text-muted-foreground">Garantia</p><p className="text-sm font-bold">{product.warrantyMonths ? `${product.warrantyMonths} meses` : "Consulte"}</p></div></div><div className="mt-7 border border-sky-200 bg-sky-50 p-5"><p className="text-sm text-muted-foreground">Condição comercial</p><p className="font-display mt-1 text-2xl font-black text-slate-950">{product.priceOnRequest ? "Preço sob consulta" : "Consulte sua tabela"}</p><p className="mt-1 text-sm text-muted-foreground">Valores podem variar conforme quantidade, região, frete e condição negociada.</p><Button asChild size="lg" className="mt-5 w-full"><a href="#solicitar">Solicitar cotação deste equipamento</a></Button></div></div></div>
  <div className="mt-12 grid gap-8 lg:grid-cols-[1fr_.72fr]"><div className="space-y-8"><section><h2 className="font-display text-2xl font-bold text-slate-950">Descrição do produto</h2><p className="mt-4 whitespace-pre-line leading-8 text-slate-700">{product.description}</p></section><Separator/><section><h2 className="font-display text-2xl font-bold text-slate-950">Especificações técnicas</h2><div className="mt-5 overflow-hidden border border-sky-200 bg-white">{specs.length ? specs.map(([key,value], i) => <div key={key} className={`grid grid-cols-[.85fr_1.15fr] gap-4 px-5 py-3.5 text-sm ${i ? "border-t" : ""}`}><span className="font-medium text-muted-foreground">{key}</span><strong>{String(value)}</strong></div>) : <p className="p-5 text-sm text-muted-foreground">Especificações sob consulta.</p>}</div></section>{dimensions.length > 0 && <><Separator/><section><h2 className="font-display text-2xl font-bold text-slate-950">Dimensões e construção</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{dimensions.map(([key,value]) => <div key={key} className="border border-sky-200 bg-white p-4"><p className="text-xs font-medium text-muted-foreground">{key}</p><p className="mt-1 font-bold">{String(value)}</p></div>)}</div></section></>}</div><div><Card className="sticky top-28 border-sky-200"><CardHeader><CardTitle className="font-display">Documentação</CardTitle></CardHeader><CardContent className="space-y-3">{product.documents.length ? product.documents.map(doc => <a key={doc.id} href={doc.url} target="_blank" className="flex items-center gap-3 border border-sky-200 p-3 transition hover:border-primary/40 hover:bg-muted"><span className="grid size-9 place-items-center bg-primary/10 text-primary"><FileText className="size-4"/></span><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{doc.title}</strong><span className="text-xs text-muted-foreground">{doc.type}{doc.version ? ` • ${doc.version}` : ""}</span></span><Download className="size-4 text-muted-foreground"/></a>) : <p className="text-sm text-muted-foreground">Documentação disponível com o atendimento comercial.</p>}<div className="mt-4 bg-sky-50 p-4 text-sm text-[var(--brand-navy)]"><CheckCircle2 className="mb-2 size-5 text-primary"/>Precisa de memorial, desenho ou documento específico? Informe no orçamento.</div></CardContent></Card></div></div>
  <section id="solicitar" className="mt-14 bg-primary p-6 text-white sm:p-10"><div className="grid gap-9 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-sky-200">Cotação personalizada</p><h2 className="font-display mt-2 text-3xl font-black">Solicite condição para {product.name}</h2><p className="mt-4 leading-7 text-sky-100">Informe seus dados e quantidade. A solicitação será registrada com o produto e código corretos.</p></div><div className="bg-white p-6 text-foreground"><QuoteForm productId={product.id} productName={product.name}/></div></div></section></main><SiteFooter/></>
}
