import { PriceUpsertForm } from "@/components/admin/price-upsert-form"
import { PageHeader } from "@/components/page-header"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { requireRole } from "@/lib/auth"
import { money } from "@/lib/format"
import { prisma } from "@/lib/prisma"

export const dynamic = "force-dynamic"

export default async function PriceTablesPage(){await requireRole(["ADMIN"]);const [tables,products]=await Promise.all([prisma.priceTable.findMany({include:{items:{include:{product:true}},_count:{select:{customers:true}}},orderBy:{name:"asc"}}),prisma.product.findMany({where:{status:"ACTIVE"},select:{id:true,name:true,sku:true},orderBy:{name:"asc"}})]);return <><PageHeader eyebrow="Política comercial" title="Tabelas de preço" description="Preços por produto, quantidade mínima e clientes vinculados." action={<PriceUpsertForm tables={tables.map(t=>({id:t.id,name:t.name}))} products={products}/>}/><div className="space-y-6">{tables.map(t=><Card key={t.id}><CardHeader className="flex-row items-center justify-between"><div><CardTitle>{t.name}</CardTitle><p className="mt-1 font-mono text-xs text-muted-foreground">{t.code} • {t._count.customers} clientes</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${t.active?"bg-emerald-100 text-emerald-800":"bg-slate-100 text-slate-600"}`}>{t.active?"Ativa":"Inativa"}</span></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>SKU / Produto</TableHead><TableHead>Quantidade mínima</TableHead><TableHead className="text-right">Preço</TableHead></TableRow></TableHeader><TableBody>{t.items.map(i=><TableRow key={i.id}><TableCell><strong>{i.product.name}</strong><div className="font-mono text-xs text-muted-foreground">{i.product.sku}</div></TableCell><TableCell>{Number(i.minQty)} {i.product.unit}</TableCell><TableCell className="text-right font-bold">{money(i.price)}</TableCell></TableRow>)}{!t.items.length&&<TableRow><TableCell colSpan={3} className="py-8 text-center text-muted-foreground">Nenhum preço cadastrado nesta tabela.</TableCell></TableRow>}</TableBody></Table></CardContent></Card>)}{!tables.length&&<Card><CardContent className="p-10 text-center text-muted-foreground">Nenhuma tabela cadastrada.</CardContent></Card>}</div></>}
