import { PrismaClient, UserRole, CustomerStatus, ProductStatus, QuoteStatus, OrderStatus, LeadStatus, CommissionStatus } from "@prisma/client";
import bcrypt from "bcryptjs";
const prisma = new PrismaClient();

const productSeeds = [
  { sku:"PGM-TRC-3000", name:"Tronco Americano de Contenção Animal", slug:"tronco-americano-de-contencao-animal", categorySlug:"troncos-de-contencao", shortDescription:"Segurança, resistência e praticidade para vacinação, marcação, inseminação, exames, casqueamento e pesagem.", description:"Projetado para oferecer segurança e praticidade no manejo do gado. Sua estrutura reforçada, portas laterais articuladas e piso antiderrapante facilitam o acesso ao animal e reduzem riscos durante os procedimentos.", heroImage:"/images/products/tronco-americano-contencao.webp", featured:true, leadTimeDays:20, warrantyMonths:24, techSpecs:{"Aplicação":"Bovinos de diferentes portes","Estrutura":"Madeira de lei e ferragens reforçadas","Acesso":"Portas laterais articuladas","Piso":"Antiderrapante"}, dimensions:{"Produção":"Sob medida","Configuração":"Conforme a necessidade da propriedade"} },
  { sku:"PGM-TRC-CREM", name:"Tronco Americano com Comandos de Cremalheira", slug:"tronco-americano-comandos-cremalheira", categorySlug:"troncos-de-contencao", shortDescription:"Travamento preciso, acesso facilitado e construção robusta para manejo seguro e eficiente.", description:"O sistema de cremalheira oferece travamento firme e controle seguro da cabeça do animal. As portas articuladas dão acesso a diferentes partes do bovino e agilizam os procedimentos de rotina.", heroImage:"/images/products/tronco-americano-cremalheira.webp", featured:true, leadTimeDays:24, warrantyMonths:24, techSpecs:{"Comando":"Cremalheira e catracas reforçadas","Estrutura":"Ferragens de alta resistência","Portas":"Madeira de lei","Acabamento":"Proteção anticorrosiva"}, dimensions:{"Produção":"Sob medida","Porte dos animais":"Pequeno, médio e grande"} },
  { sku:"PGM-TRC-MAD", name:"Tronco Americano em Madeira Maciça", slug:"tronco-americano-madeira-macica", categorySlug:"troncos-de-contencao", shortDescription:"Madeira de lei, comandos de cremalheira e acabamento resistente para uso intenso no campo.", description:"Construído em madeira maciça, combina estabilidade, durabilidade e controle. A madeira é tratada e envernizada conforme a preferência do cliente, com ferragens reforçadas e piso seguro.", heroImage:"/images/products/tronco-madeira-macica.webp", featured:false, leadTimeDays:24, warrantyMonths:24, techSpecs:{"Material":"Madeira de lei maciça","Comando":"Cremalheira","Ferragens":"Reforçadas","Acabamento":"Tratado e envernizado"}, dimensions:{"Produção":"Sob medida","Configuração":"Personalizável"} },
  { sku:"PGM-TRC-PRO", name:"Tronco com Pistão e Cabine Traseira", slug:"tronco-pistao-cabine-traseira", categorySlug:"troncos-de-contencao", shortDescription:"Modelo versátil com pistão e cabine traseira para maior controle e conforto durante o manejo.", description:"Combina a praticidade de um tronco tradicional com recursos adicionais que facilitam o trabalho diário. A cabine traseira oferece mais controle ao operador, mantendo robustez e segurança.", heroImage:"/images/products/tronco-pistao-cabine.webp", featured:true, leadTimeDays:25, warrantyMonths:24, techSpecs:{"Sistema":"Pistão","Cabine":"Traseira","Aplicação":"Manejo bovino","Construção":"Madeira e ferragens reforçadas"}, dimensions:{"Produção":"Sob medida","Acabamento":"Conforme preferência do cliente"} },
  { sku:"PGM-BAL-1500", name:"Balança Mecânica de 1.500 kg", slug:"balanca-mecanica-1500kg", categorySlug:"balancas-pecuarias", shortDescription:"Pesagem prática de pequenos animais, com gaiola em madeira de lei e portas de correr.", description:"Balança mecânica com capacidade para até 1.500 kg. A gaiola reforçada e as portas de correr facilitam a entrada e saída dos animais, tornando a pesagem mais rápida e segura.", heroImage:"/images/products/balanca-mecanica-1500.webp", featured:true, leadTimeDays:15, warrantyMonths:18, techSpecs:{"Capacidade":"1.500 kg","Aplicação":"Até 5 bezerros pequenos","Gaiola":"Madeira de lei","Portas":"De correr"}, dimensions:{"Produção":"Sob encomenda","Acabamento":"Madeira tratada e ferragem protegida"} },
  { sku:"PGM-BAL-3000", name:"Balança Mecânica de 3.000 kg", slug:"balanca-mecanica-3000kg", categorySlug:"balancas-pecuarias", shortDescription:"Alta resistência para pesagem de até cinco animais de médio porte ao mesmo tempo.", description:"Com capacidade para 3.000 kg, é indicada para propriedades que precisam pesar lotes com agilidade. A gaiola em madeira de lei e as portas de correr oferecem robustez e praticidade.", heroImage:"/images/products/balanca-mecanica-3000.webp", featured:false, leadTimeDays:18, warrantyMonths:18, techSpecs:{"Capacidade":"3.000 kg","Aplicação":"Até 5 animais de médio porte","Gaiola":"Madeira de lei","Portas":"De correr"}, dimensions:{"Produção":"Sob encomenda","Acabamento":"Madeira tratada e ferragem protegida"} },
  { sku:"PGM-BRT-MOD", name:"Gradil com Balança Eletrônica", slug:"gradil-com-balanca-eletronica", categorySlug:"bretes-e-corredores", shortDescription:"Chassi elevado preparado para barras eletrônicas, com manejo rápido, seguro e preciso.", description:"Desenvolvido para pequenas e médias propriedades, o gradil possui chassi elevado para instalação imediata das barras de pesagem eletrônica. O conjunto facilita a operação e a manutenção.", heroImage:"/images/products/gradil-balanca-eletronica.webp", featured:true, leadTimeDays:16, warrantyMonths:18, techSpecs:{"Pesagem":"Eletrônica","Chassi":"Elevado","Instalação":"Preparado para barras de pesagem","Uso":"Manejo diário"}, dimensions:{"Produção":"Sob encomenda","Configuração":"Adaptável à propriedade"} },
  { sku:"PGM-PAS-LAT", name:"Pescoceira para Manejo Bovino", slug:"pescoceira-manejo-bovino", categorySlug:"bretes-e-corredores", shortDescription:"Contenção segura e confortável para animais de pequeno, médio e grande porte.", description:"A pescoceira facilita vacinação, pesagem, exames e tratamentos. Seu sistema ajustável ajuda a reduzir o estresse do animal e dá mais segurança ao operador.", heroImage:"/images/products/pescoceira.webp", featured:false, leadTimeDays:10, warrantyMonths:12, techSpecs:{"Aplicação":"Bovinos e búfalos","Ajuste":"Diferentes portes","Uso":"Vacinação, exames e tratamentos","Construção":"Madeira e ferragens reforçadas"}, dimensions:{"Produção":"Sob medida","Modelo reforçado":"Disponível para búfalos"} },
  { sku:"PGM-POR-GUIL", name:"Porteira de Madeira", slug:"porteira-de-madeira", categorySlug:"porteiras-e-acessorios", shortDescription:"Madeira de lei, construção firme e acabamento superior para organizar o fluxo do rebanho.", description:"Porteira fabricada para suportar o uso intenso na propriedade rural. A madeira de lei recebe tratamento e acabamento para maior durabilidade.", heroImage:"/images/products/porteira-madeira.webp", featured:false, leadTimeDays:10, warrantyMonths:12, techSpecs:{"Material":"Madeira de lei","Aplicação":"Curral e propriedade rural","Acabamento":"Tratado e envernizado","Produção":"Sob medida"}, dimensions:{"Largura":"Conforme o vão","Altura":"Conforme o projeto"} },
  { sku:"PGM-POR-TUB", name:"Porteira Tubular Reforçada", slug:"porteira-tubular-reforcada", categorySlug:"porteiras-e-acessorios", shortDescription:"Estrutura metálica resistente para controle de acesso e organização do curral.", description:"Modelo tubular com construção reforçada e acabamento de proteção, indicado para áreas de manejo e acessos da propriedade.", heroImage:"/images/products/porteira-tubular.webp", featured:false, leadTimeDays:10, warrantyMonths:12, techSpecs:{"Estrutura":"Tubular metálica","Aplicação":"Curral e acessos","Acabamento":"Pintura de proteção","Produção":"Sob medida"}, dimensions:{"Largura":"Conforme o vão","Altura":"Conforme o projeto"} },
  { sku:"PGM-KIT-IND", name:"Kit de Barras de Pesagem + Indicador", slug:"kit-barras-pesagem-indicador", categorySlug:"pecas-e-eletronica", shortDescription:"Conjunto eletrônico para modernização ou instalação de sistemas de pesagem pecuária.", description:"Kit com barras, cabos e indicador para compor sistemas de pesagem. Consulte a configuração adequada à capacidade e ao equipamento da propriedade.", heroImage:"/images/products/barras-pesagem.webp", featured:false, leadTimeDays:5, warrantyMonths:12, techSpecs:{"Kit":"Barras, cabos e indicador","Aplicação":"Balanças pecuárias","Instalação":"Conforme equipamento","Alimentação":"Consulte"}, dimensions:{"Capacidade":"Conforme o modelo","Embalagem":"Kit completo"} },
  { sku:"PGM-IND-ELE", name:"Indicador Eletrônico de Pesagem", slug:"indicador-eletronico-pesagem", categorySlug:"pecas-e-eletronica", shortDescription:"Leitura clara e operação prática para sistemas eletrônicos de pesagem no campo.", description:"Indicador desenvolvido para integrar sistemas de pesagem pecuária, com comandos de fácil acesso e visor de leitura rápida.", heroImage:"/images/products/indicador-eletronico.webp", featured:false, leadTimeDays:5, warrantyMonths:12, techSpecs:{"Aplicação":"Pesagem pecuária","Visor":"Digital","Comandos":"Painel frontal","Conexão":"Conforme o kit"}, dimensions:{"Instalação":"Painel ou suporte","Compatibilidade":"Consulte"} },
  { sku:"PGM-CEL-CARGA", name:"Célula de Carga para Balança", slug:"celula-de-carga-balanca", categorySlug:"pecas-e-eletronica", shortDescription:"Componente de reposição para sistemas de pesagem, disponível em diferentes capacidades.", description:"Célula de carga para manutenção, reposição ou montagem de conjuntos eletrônicos de pesagem. A capacidade deve ser escolhida conforme o projeto da balança.", heroImage:"/images/products/celula-carga.webp", featured:false, leadTimeDays:5, warrantyMonths:12, techSpecs:{"Aplicação":"Balanças pecuárias","Tipo":"Célula de carga","Capacidade":"Conforme o modelo","Instalação":"Técnica"}, dimensions:{"Modelo":"Sob consulta","Conector":"Conforme aplicação"} },
  { sku:"PGM-CON-C016", name:"Conector C016 para Balança", slug:"conector-c016-balanca", categorySlug:"pecas-e-eletronica", shortDescription:"Conector macho, painel fêmea e tampa para manutenção da linha eletrônica.", description:"Componentes C016 para conexão e proteção dos sistemas eletrônicos de pesagem. Consulte a opção necessária para o seu equipamento.", heroImage:"/images/products/conector-c016.webp", featured:false, leadTimeDays:5, warrantyMonths:6, techSpecs:{"Linha":"C016","Opções":"Macho, painel fêmea e tampa","Aplicação":"Sistemas de pesagem","Venda":"Por componente"}, dimensions:{"Modelo":"C016","Compatibilidade":"Consulte"} }
];

async function main() {
  const hash = await bcrypt.hash("Pgm@2026", 12);
  const admin = await prisma.user.upsert({ where:{email:"admin@pgm.local"}, update:{name:"Administrador PGM",role:UserRole.ADMIN,active:true,passwordHash:hash}, create:{name:"Administrador PGM",email:"admin@pgm.local",passwordHash:hash,role:UserRole.ADMIN} });
  const repUser = await prisma.user.upsert({ where:{email:"representante@pgm.local"}, update:{name:"Atendimento PGM",role:UserRole.REPRESENTATIVE,active:true,passwordHash:hash,phone:"(91) 99215-4103"}, create:{name:"Atendimento PGM",email:"representante@pgm.local",passwordHash:hash,role:UserRole.REPRESENTATIVE,phone:"(91) 99215-4103"} });
  const rep = await prisma.representative.upsert({ where:{userId:repUser.id}, update:{code:"REP-PA-01",region:"Paragominas e região",states:["PA"],commissionRate:4.5,active:true}, create:{userId:repUser.id,code:"REP-PA-01",region:"Paragominas e região",states:["PA"],commissionRate:4.5} });
  const clientUser = await prisma.user.upsert({ where:{email:"cliente@pgm.local"}, update:{name:"Fazenda Santa Clara",role:UserRole.CUSTOMER,active:true,passwordHash:hash}, create:{name:"Fazenda Santa Clara",email:"cliente@pgm.local",passwordHash:hash,role:UserRole.CUSTOMER,phone:"(18) 99999-2000"} });
  const table = await prisma.priceTable.upsert({ where:{code:"PADRAO"}, update:{name:"Tabela Padrão",active:true}, create:{code:"PADRAO",name:"Tabela Padrão"} });
  const customer = await prisma.customer.upsert({ where:{document:"12.345.678/0001-90"}, update:{userId:clientUser.id,representativeId:rep.id,priceTableId:table.id,status:CustomerStatus.ACTIVE}, create:{userId:clientUser.id,representativeId:rep.id,priceTableId:table.id,legalName:"Fazenda Santa Clara Agropecuária Ltda",tradeName:"Fazenda Santa Clara",document:"12.345.678/0001-90",email:"cliente@pgm.local",phone:"(18) 99999-2000",whatsapp:"(18) 99999-2000",city:"Presidente Prudente",state:"SP",segment:"Pecuária de corte",status:CustomerStatus.ACTIVE,creditLimit:150000} });
  if (!(await prisma.address.count({where:{customerId:customer.id}}))) await prisma.address.create({data:{customerId:customer.id,label:"Fazenda",postalCode:"19000-000",street:"Rodovia Vicinal PGM",number:"Km 12",district:"Zona Rural",city:"Presidente Prudente",state:"SP",isDefault:true}});
  if (!(await prisma.customerDocument.count({where:{customerId:customer.id}}))) await prisma.customerDocument.create({data:{customerId:customer.id,title:"Guia de pós-venda PGM",type:"HTML",url:"/documentos/pos-venda-demo.html",issuedAt:new Date()}});

  const cats = [
    ["Troncos de Contenção","troncos-de-contencao","Equipamentos robustos para manejo bovino com segurança e ergonomia.","PanelsTopLeft",10],
    ["Balanças Pecuárias","balancas-pecuarias","Sistemas completos de pesagem para curral, fazenda e centros de manejo.","Scale",20],
    ["Gradis e Manejo","bretes-e-corredores","Gradis, pescoceiras e soluções para fluxo, organização e segurança no curral.","Fence",30],
    ["Porteiras e Acessórios","porteiras-e-acessorios","Porteiras, travas e componentes para completar a estrutura de manejo.","BetweenHorizontalStart",40],
    ["Linha Eletrônica","pecas-e-eletronica","Indicadores, barras, células de carga, conectores e componentes de manutenção.","CircuitBoard",50]
  ] as const;
  const catIds:Record<string,string>={};
  for (const [name,slug,description,icon,sortOrder] of cats) {
    const c=await prisma.category.upsert({where:{slug},update:{name,description,icon,sortOrder,active:true},create:{name,slug,description,icon,sortOrder}}); catIds[slug]=c.id;
  }
  for (const item of productSeeds) {
    const product=await prisma.product.upsert({where:{sku:item.sku},update:{categoryId:catIds[item.categorySlug],name:item.name,slug:item.slug,shortDescription:item.shortDescription,description:item.description,heroImage:item.heroImage,status:ProductStatus.ACTIVE,featured:item.featured,priceOnRequest:true,stockStatus:"Produção sob pedido",leadTimeDays:item.leadTimeDays,warrantyMonths:item.warrantyMonths,techSpecs:item.techSpecs,dimensions:item.dimensions},create:{categoryId:catIds[item.categorySlug],sku:item.sku,name:item.name,slug:item.slug,shortDescription:item.shortDescription,description:item.description,heroImage:item.heroImage,status:ProductStatus.ACTIVE,featured:item.featured,priceOnRequest:true,stockStatus:"Produção sob pedido",leadTimeDays:item.leadTimeDays,warrantyMonths:item.warrantyMonths,techSpecs:item.techSpecs,dimensions:item.dimensions}});
    if (!(await prisma.productDocument.count({where:{productId:product.id}}))) await prisma.productDocument.create({data:{productId:product.id,title:"Ficha técnica demonstrativa",type:"HTML",url:"/documentos/ficha-tecnica-demo.html",version:"1.0",isPublic:true}});
  }
  const p=await prisma.product.findUnique({where:{sku:"PGM-TRC-3000"}});
  if (p) {
    await prisma.priceTableItem.upsert({where:{priceTableId_productId:{priceTableId:table.id,productId:p.id}},update:{price:28900},create:{priceTableId:table.id,productId:p.id,price:28900}});
    const q=await prisma.quote.upsert({where:{number:"ORC-2026-0001"},update:{customerId:customer.id,representativeId:rep.id,createdById:repUser.id,status:QuoteStatus.SENT,subtotal:28900,total:28900},create:{number:"ORC-2026-0001",customerId:customer.id,representativeId:rep.id,createdById:repUser.id,status:QuoteStatus.SENT,validUntil:new Date(Date.now()+10*86400000),subtotal:28900,total:28900,commercialTerms:"30% de entrada + saldo antes do embarque."}});
    if (!(await prisma.quoteItem.findFirst({where:{quoteId:q.id,productId:p.id}}))) await prisma.quoteItem.create({data:{quoteId:q.id,productId:p.id,quantity:1,unitPrice:28900,total:28900}});
    const o=await prisma.order.upsert({where:{number:"PED-2026-0001"},update:{customerId:customer.id,representativeId:rep.id,status:OrderStatus.IN_PRODUCTION,subtotal:28900,total:28900},create:{number:"PED-2026-0001",customerId:customer.id,representativeId:rep.id,status:OrderStatus.IN_PRODUCTION,subtotal:28900,total:28900,paymentTerms:"30/70",deliveryForecast:new Date(Date.now()+18*86400000)}});
    if (!(await prisma.orderItem.findFirst({where:{orderId:o.id,productId:p.id}}))) await prisma.orderItem.create({data:{orderId:o.id,productId:p.id,quantity:1,unitPrice:28900,total:28900}});
    if (!(await prisma.commission.findFirst({where:{representativeId:rep.id,orderId:o.id}}))) await prisma.commission.create({data:{representativeId:rep.id,orderId:o.id,competence:"2026-08",percentage:4.5,baseAmount:28900,amount:1300.5,status:CommissionStatus.FORECAST}});
  }
  if (!(await prisma.lead.count({where:{representativeId:rep.id}}))) await prisma.lead.createMany({data:[{representativeId:rep.id,companyName:"Fazenda Horizonte",contactName:"Marcos Oliveira",phone:"(18) 98888-0101",email:"marcos@example.com",city:"Rancharia",state:"SP",source:"Feira agro",status:LeadStatus.QUALIFIED,valueEstimate:45000,nextActionAt:new Date(Date.now()+2*86400000)},{representativeId:rep.id,companyName:"Agropecuária Boa Safra",contactName:"Patrícia Souza",phone:"(67) 98888-0202",city:"Campo Grande",state:"MS",source:"Indicação",status:LeadStatus.PROPOSAL,valueEstimate:72000}]});
  await prisma.companySetting.upsert({where:{key:"company"},update:{value:{companyName:"Troncos e Balanças Paragominas",phone:"(91) 99342-8963",secondaryPhone:"(91) 99215-4103",whatsapp:"5591993428963",email:"ozielvasconscelos2014@gmail.com",city:"Paragominas",state:"PA"}},create:{key:"company",value:{companyName:"Troncos e Balanças Paragominas",phone:"(91) 99342-8963",secondaryPhone:"(91) 99215-4103",whatsapp:"5591993428963",email:"ozielvasconscelos2014@gmail.com",city:"Paragominas",state:"PA"}}});
  console.log("Seed PGM concluído. Usuários demo com senha Pgm@2026:", admin.email, repUser.email, clientUser.email);
}
main().catch(e=>{console.error(e);process.exit(1)}).finally(()=>prisma.$disconnect());
