"use client"
import { useRouter } from "next/navigation"
import { useState } from "react"
import { Loader2, Plus } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

export function CustomerCreateForm({representatives,priceTables}:{representatives:{id:string;name:string}[];priceTables:{id:string;name:string}[]}){const router=useRouter();const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function submit(fd:FormData){setBusy(true);setError("");const r=await fetch("/api/admin/customers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(fd.entries()))});const d=await r.json();setBusy(false);if(!r.ok)return setError(d.error||"Falha");setOpen(false);router.refresh()}return !open?<Button onClick={()=>setOpen(true)}><Plus/>Novo cliente</Button>:<div className="w-full rounded-xl border bg-white p-5 shadow-sm"><div className="mb-4 flex justify-between"><strong>Novo cliente e acesso</strong><Button variant="ghost" size="sm" onClick={()=>setOpen(false)}>Cancelar</Button></div><form action={submit} className="grid gap-3 md:grid-cols-2"><div className="grid gap-2"><Label>Razão social</Label><Input name="legalName" required/></div><div className="grid gap-2"><Label>Nome fantasia</Label><Input name="tradeName"/></div><div className="grid gap-2"><Label>CNPJ / CPF</Label><Input name="document" required/></div><div className="grid gap-2"><Label>Segmento</Label><Input name="segment" placeholder="Pecuária de corte"/></div><div className="grid gap-2"><Label>E-mail / login</Label><Input name="email" type="email" required/></div><div className="grid gap-2"><Label>Senha inicial</Label><Input name="password" type="text" minLength={6} required/></div><div className="grid gap-2"><Label>Telefone</Label><Input name="phone" required/></div><div className="grid gap-2"><Label>WhatsApp</Label><Input name="whatsapp"/></div><div className="grid gap-2"><Label>Cidade</Label><Input name="city" required/></div><div className="grid gap-2"><Label>UF</Label><Input name="state" maxLength={2} required/></div><div className="grid gap-2"><Label>Representante</Label><select name="representativeId" className="h-10 rounded-lg border bg-white px-3 text-sm"><option value="">Central</option>{representatives.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></div><div className="grid gap-2"><Label>Tabela de preço</Label><select name="priceTableId" className="h-10 rounded-lg border bg-white px-3 text-sm"><option value="">Padrão não vinculada</option>{priceTables.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div>{error&&<p className="text-sm text-destructive md:col-span-2">{error}</p>}<Button className="md:col-span-2" disabled={busy}>{busy&&<Loader2 className="animate-spin"/>}Criar cliente</Button></form></div>}
