"use client"
import { useRouter } from "next/navigation"
import { useState } from "react"
import { Loader2, UploadCloud } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

export function DocumentUploadForm({products,customers}:{products:{id:string;name:string;sku:string}[];customers:{id:string;name:string}[]}){const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function submit(fd:FormData){setBusy(true);setError("");const r=await fetch("/api/admin/uploads",{method:"POST",body:fd});const data=await r.json();setBusy(false);if(!r.ok)return setError(data.error||"Falha no upload");(document.getElementById("doc-upload-form") as HTMLFormElement)?.reset();router.refresh()}return <form id="doc-upload-form" action={submit} className="grid gap-4 md:grid-cols-2"><div className="grid gap-2"><Label>Destino</Label><select name="targetType" className="h-10 rounded-lg border bg-white px-3 text-sm" required><option value="product">Produto / catálogo</option><option value="customer">Cliente</option></select></div><div className="grid gap-2"><Label>Tipo do documento</Label><Input name="type" placeholder="Manual, Certificado, Laudo..." required/></div><div className="grid gap-2 md:col-span-2"><Label>Produto</Label><select name="productId" className="h-10 rounded-lg border bg-white px-3 text-sm"><option value="">Selecione se o destino for produto</option>{products.map(p=><option key={p.id} value={p.id}>{p.sku} • {p.name}</option>)}</select></div><div className="grid gap-2 md:col-span-2"><Label>Cliente</Label><select name="customerId" className="h-10 rounded-lg border bg-white px-3 text-sm"><option value="">Selecione se o destino for cliente</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="grid gap-2"><Label>Título</Label><Input name="title" required/></div><div className="grid gap-2"><Label>Versão (opcional)</Label><Input name="version"/></div><div className="grid gap-2 md:col-span-2"><Label>Arquivo</Label><Input name="file" type="file" required/></div><label className="flex items-center gap-2 text-sm md:col-span-2"><input type="checkbox" name="isPublic" value="true"/> Documento público no catálogo (somente produto)</label>{error&&<p className="text-sm text-destructive md:col-span-2">{error}</p>}<Button disabled={busy} className="md:col-span-2">{busy?<Loader2 className="animate-spin"/>:<UploadCloud/>}Enviar e vincular documento</Button></form>}
