"use client"
import { useRouter } from "next/navigation"
import { useState } from "react"
import { Loader2, Plus } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"

export function ProductCreateForm({categories}:{categories:{id:string;name:string}[]}){const router=useRouter();const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function submit(fd:FormData){setBusy(true);setError("");const r=await fetch("/api/admin/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(fd.entries()))});const data=await r.json();setBusy(false);if(!r.ok)return setError(data.error||"Falha ao cadastrar");setOpen(false);router.refresh()}return <div>{!open?<Button onClick={()=>setOpen(true)}><Plus/>Novo produto</Button>:<div className="w-full rounded-xl border bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><strong>Novo produto</strong><Button size="sm" variant="ghost" onClick={()=>setOpen(false)}>Cancelar</Button></div><form action={submit} className="grid gap-4 md:grid-cols-2"><div className="grid gap-2"><Label>SKU</Label><Input name="sku" required/></div><div className="grid gap-2"><Label>Categoria</Label><select name="categoryId" required className="h-10 rounded-lg border bg-white px-3 text-sm">{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="grid gap-2 md:col-span-2"><Label>Nome</Label><Input name="name" required/></div><div className="grid gap-2 md:col-span-2"><Label>Resumo</Label><Input name="shortDescription" required/></div><div className="grid gap-2 md:col-span-2"><Label>Descrição</Label><Textarea name="description" required/></div><div className="grid gap-2"><Label>Prazo (dias)</Label><Input type="number" name="leadTimeDays" defaultValue="20"/></div><div className="grid gap-2"><Label>Garantia (meses)</Label><Input type="number" name="warrantyMonths" defaultValue="12"/></div>{error&&<p className="text-sm text-destructive md:col-span-2">{error}</p>}<Button disabled={busy} className="md:col-span-2">{busy&&<Loader2 className="animate-spin"/>}Cadastrar produto</Button></form></div>}</div>}
