"use client"
import { useRouter } from "next/navigation"
import { useState } from "react"
import { Loader2, Plus } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

export function RepresentativeCreateForm(){const router=useRouter();const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function submit(fd:FormData){setBusy(true);setError("");const r=await fetch("/api/admin/representatives",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(fd.entries()))});const d=await r.json();setBusy(false);if(!r.ok)return setError(d.error||"Falha");setOpen(false);router.refresh()}return !open?<Button onClick={()=>setOpen(true)}><Plus/>Novo representante</Button>:<div className="w-full rounded-xl border bg-white p-5 shadow-sm"><div className="mb-4 flex justify-between"><strong>Novo representante e acesso</strong><Button variant="ghost" size="sm" onClick={()=>setOpen(false)}>Cancelar</Button></div><form action={submit} className="grid gap-3 md:grid-cols-2"><div className="grid gap-2"><Label>Nome</Label><Input name="name" required/></div><div className="grid gap-2"><Label>Código</Label><Input name="code" placeholder="REP-SP-02" required/></div><div className="grid gap-2"><Label>E-mail / login</Label><Input name="email" type="email" required/></div><div className="grid gap-2"><Label>Senha inicial</Label><Input name="password" minLength={6} required/></div><div className="grid gap-2"><Label>Telefone</Label><Input name="phone"/></div><div className="grid gap-2"><Label>Região</Label><Input name="region" placeholder="Noroeste Paulista" required/></div><div className="grid gap-2"><Label>UFs (separadas por vírgula)</Label><Input name="states" placeholder="SP, MG" required/></div><div className="grid gap-2"><Label>Comissão padrão (%)</Label><Input name="commissionRate" type="number" step="0.01" min="0" max="100" defaultValue="4.5" required/></div>{error&&<p className="text-sm text-destructive md:col-span-2">{error}</p>}<Button className="md:col-span-2" disabled={busy}>{busy&&<Loader2 className="animate-spin"/>}Criar representante</Button></form></div>}
