import Link from "next/link"
import { Boxes, Building2, CircleDollarSign, PackageCheck, ReceiptText, UsersRound } from "lucide-react"
import { PageHeader } from "@/components/page-header"
import { StatCard } from "@/components/stat-card"
import { StatusBadge } from "@/components/status-badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { requireRole } from "@/lib/auth"
import { dateBR, money } from "@/lib/format"
import { prisma } from "@/lib/prisma"

export const dynamic = "force-dynamic"

export default async function AdminDashboard(){await requireRole(["ADMIN"]);const [products,customers,reps,quotes,orders]=await Promise.all([prisma.product.count({where:{status:"ACTIVE"}}),prisma.customer.count({where:{status:"ACTIVE"}}),prisma.representative.count({where:{active:true}}),prisma.quote.findMany({include:{customer:true},orderBy:{createdAt:"desc"},take:8}),prisma.order.findMany({include:{customer:true},orderBy:{createdAt:"desc"},take:8})]);const orderValue=orders.reduce((a,o)=>a+Number(o.total),0);const openQuotes=quotes.filter(q=>!["REJECTED","EXPIRED","CONVERTED"].includes(q.status)).length;return <><PageHeader eyebrow="Central de gestão" title="Painel administrativo" description="Visão geral da operação comercial, catálogo e rede de atendimento PGM."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><StatCard label="Produtos ativos" value={String(products)} icon={Boxes}/><StatCard label="Clientes ativos" value={String(customers)} icon={Building2}/><StatCard label="Representantes" value={String(reps)} icon={UsersRound}/><StatCard label="Orçamentos abertos" value={String(openQuotes)} icon={ReceiptText}/><StatCard label="Pedidos recentes" value={String(orders.length)} icon={PackageCheck}/><StatCard label="Volume recente" value={money(orderValue)} icon={CircleDollarSign}/></div><div className="mt-7 grid gap-6 xl:grid-cols-2"><Card><CardHeader className="flex-row items-center justify-between"><CardTitle>Fila de orçamentos</CardTitle><Link href="/admin/orcamentos" className="text-sm font-semibold text-primary">Gerenciar</Link></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Número / cliente</TableHead><TableHead>Status</TableHead><TableHead>Total</TableHead></TableRow></TableHeader><TableBody>{quotes.slice(0,6).map(q=><TableRow key={q.id}><TableCell><strong>{q.number}</strong><div className="text-xs text-muted-foreground">{q.customer?.tradeName||q.prospectName||"Solicitação"} • {dateBR(q.createdAt)}</div></TableCell><TableCell><StatusBadge status={q.status}/></TableCell><TableCell className="font-semibold">{money(q.total)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card><Card><CardHeader className="flex-row items-center justify-between"><CardTitle>Produção e expedição</CardTitle><Link href="/admin/pedidos" className="text-sm font-semibold text-primary">Gerenciar</Link></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Pedido / cliente</TableHead><TableHead>Status</TableHead><TableHead>Total</TableHead></TableRow></TableHeader><TableBody>{orders.slice(0,6).map(o=><TableRow key={o.id}><TableCell><strong>{o.number}</strong><div className="text-xs text-muted-foreground">{o.customer.tradeName||o.customer.legalName} • {dateBR(o.createdAt)}</div></TableCell><TableCell><StatusBadge status={o.status}/></TableCell><TableCell className="font-semibold">{money(o.total)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div></>}
