import Image from "next/image"
import Link from "next/link"
import { Factory, Headphones, MapPin, ShieldCheck, Wrench } from "lucide-react"
import { SiteHeader } from "@/components/site-header"
import { SiteFooter } from "@/components/site-footer"
import { Button } from "@/components/ui/button"

export default function EmpresaPage() {
  return <><SiteHeader/><main>
    <section className="relative overflow-hidden border-b border-sky-200 bg-white"><div className="catalog-dots absolute right-10 top-8 h-44 w-44 opacity-30"/><div className="container-wide grid items-center gap-12 py-16 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-primary">Troncos e Balanças Paragominas</p><h1 className="font-display mt-3 text-4xl font-black leading-tight text-slate-950 sm:text-5xl">Fabricamos soluções para a rotina real do campo.</h1><div className="brand-rule mt-5"/><p className="mt-6 text-lg leading-8 text-slate-600">A PGM desenvolve e fabrica equipamentos para contenção, pesagem e organização do manejo bovino, unindo madeira de lei, ferragens reforçadas e experiência prática.</p><div className="mt-7 flex items-center gap-3 text-sm font-bold text-[var(--brand-navy)]"><MapPin className="size-5 text-primary"/>Paragominas • Pará</div></div><div className="relative min-h-[430px] border-[8px] border-sky-100"><Image src="/images/products/tronco-madeira-macica.webp" alt="Tronco Americano em madeira maciça fabricado em Paragominas" fill priority sizes="(max-width: 1024px) 100vw, 55vw" className="object-cover"/></div></div></section>
    <section className="container-wide grid gap-12 py-20 lg:grid-cols-[.88fr_1.12fr]"><div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-primary">Nosso compromisso</p><h2 className="font-display mt-2 text-3xl font-black text-slate-950">Qualidade que aparece na construção e no trabalho diário.</h2><div className="brand-rule-sky mt-5"/><p className="mt-6 leading-8 text-slate-600">Os equipamentos são produzidos para oferecer segurança ao animal e ao operador, facilitar os procedimentos de manejo e suportar uso intenso. O atendimento acontece diretamente com quem conhece o produto e sua fabricação.</p><Button asChild className="mt-7"><Link href="/catalogo">Conhecer o catálogo</Link></Button></div><div className="grid gap-4 sm:grid-cols-2">{[[Factory,"Fabricação própria","Produção e acabamento acompanhados de perto."],[ShieldCheck,"Segurança no manejo","Estruturas firmes e operação confiável."],[Wrench,"Resistência e manutenção","Materiais selecionados para longa durabilidade."],[Headphones,"Atendimento direto","Orientação para escolher o equipamento adequado."]].map(([Icon,title,text])=>{const I=Icon as typeof Factory;return <div key={String(title)} className="border border-sky-200 bg-white p-6"><I className="size-7 text-primary"/><h3 className="font-display mt-5 text-xl font-bold text-slate-950">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{String(text)}</p></div>})}</div></section>
    <section className="bg-sky-50 py-20"><div className="container-wide grid items-center gap-10 lg:grid-cols-[1.08fr_.92fr]"><div className="relative min-h-[400px]"><Image src="/images/products/tronco-pistao-cabine.webp" alt="Tronco com pistão e cabine traseira PGM" fill sizes="(max-width: 1024px) 100vw, 55vw" className="object-cover"/></div><div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-primary">Do projeto ao pós-venda</p><h2 className="font-display mt-2 text-3xl font-black text-slate-950">Uma relação construída junto com o produtor.</h2><div className="brand-rule mt-5"/><p className="mt-6 leading-8 text-slate-600">O cliente pode conhecer as opções, solicitar orçamento, acompanhar pedidos e manter documentos em uma única plataforma. Nossa tecnologia organiza o atendimento sem tirar a proximidade da conversa direta.</p><Button asChild size="lg" className="mt-7"><Link href="/contato">Conversar com a PGM</Link></Button></div></div></section>
  </main><SiteFooter/></>
}
