import { MapPin, UserRound } from "lucide-react"
import { PageHeader } from "@/components/page-header"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { requireRole } from "@/lib/auth"
import { prisma } from "@/lib/prisma"
import { money } from "@/lib/format"

export const dynamic = "force-dynamic"

export default async function CustomerProfile(){const user=await requireRole(["CUSTOMER"]);const customer=user.customer?await prisma.customer.findUnique({where:{id:user.customer.id},include:{addresses:true,representative:{include:{user:true}},priceTable:true}}):null;if(!customer)return <PageHeader title="Empresa não vinculada"/>;return <><PageHeader eyebrow="Cadastro" title={customer.tradeName||customer.legalName} description={customer.legalName}/><div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><UserRound className="size-5 text-primary"/>Dados comerciais</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2">{[["CNPJ/CPF",customer.document],["E-mail",customer.email],["Telefone",customer.phone],["Cidade",`${customer.city}/${customer.state}`],["Tabela de preço",customer.priceTable?.name||"Padrão"],["Limite de crédito",customer.creditLimit?money(customer.creditLimit):"Sob análise"],["Representante",customer.representative?.user.name||"Central"],["Segmento",customer.segment||"—"]].map(([k,v])=><div key={String(k)}><p className="text-xs font-medium text-muted-foreground">{String(k)}</p><p className="mt-1 font-semibold">{String(v)}</p></div>)}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><MapPin className="size-5 text-primary"/>Endereços</CardTitle></CardHeader><CardContent className="space-y-3">{customer.addresses.map(a=><div key={a.id} className="rounded-lg border p-4"><div className="flex items-center justify-between"><strong>{a.label}</strong>{a.isDefault&&<span className="rounded-full bg-primary/10 px-2 py-1 text-xs font-semibold text-primary">Principal</span>}</div><p className="mt-2 text-sm leading-6 text-muted-foreground">{a.street}, {a.number}{a.complement?`, ${a.complement}`:""}<br/>{a.district} • {a.city}/{a.state} • CEP {a.postalCode}</p></div>)}</CardContent></Card></div></>}
