import Link from "next/link"
import { CircleDollarSign, ContactRound, ReceiptText, UsersRound } from "lucide-react"
import { PageHeader } from "@/components/page-header"
import { StatCard } from "@/components/stat-card"
import { StatusBadge } from "@/components/status-badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { requireRole } from "@/lib/auth"
import { dateBR, money } from "@/lib/format"
import { prisma } from "@/lib/prisma"

export const dynamic = "force-dynamic"

export default async function RepDashboard(){const user=await requireRole(["REPRESENTATIVE"]);const rep=user.representative;if(!rep)return <PageHeader title="Representante não vinculado"/>;const [customers,leads,quotes,commissions]=await Promise.all([prisma.customer.count({where:{representativeId:rep.id,status:"ACTIVE"}}),prisma.lead.findMany({where:{representativeId:rep.id},orderBy:{updatedAt:"desc"},take:6}),prisma.quote.findMany({where:{representativeId:rep.id},orderBy:{createdAt:"desc"},take:6}),prisma.commission.findMany({where:{representativeId:rep.id},orderBy:{createdAt:"desc"}})]);const pipeline=leads.reduce((a,l)=>a+Number(l.valueEstimate||0),0);const commissionOpen=commissions.filter(c=>c.status!=="PAID").reduce((a,c)=>a+Number(c.amount),0);return <><PageHeader eyebrow={rep.code} title={`Comercial • ${rep.region}`} description={`Território: ${rep.states.join(", ")} • comissão padrão ${Number(rep.commissionRate).toFixed(1)}%`}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Clientes ativos" value={String(customers)} icon={UsersRound}/><StatCard label="Leads no radar" value={String(leads.length)} helper={money(pipeline)+" em potencial"} icon={ContactRound}/><StatCard label="Orçamentos recentes" value={String(quotes.length)} icon={ReceiptText}/><StatCard label="Comissão prevista" value={money(commissionOpen)} icon={CircleDollarSign}/></div><div className="mt-7 grid gap-6 xl:grid-cols-2"><Card><CardHeader className="flex-row items-center justify-between"><CardTitle>Pipeline de leads</CardTitle><Link href="/representante/leads" className="text-sm font-semibold text-primary">Abrir CRM</Link></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Empresa</TableHead><TableHead>Status</TableHead><TableHead>Potencial</TableHead></TableRow></TableHeader><TableBody>{leads.map(l=><TableRow key={l.id}><TableCell><strong>{l.companyName}</strong><div className="text-xs text-muted-foreground">{l.city}/{l.state}</div></TableCell><TableCell><StatusBadge status={l.status}/></TableCell><TableCell className="font-semibold">{money(l.valueEstimate)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card><Card><CardHeader className="flex-row items-center justify-between"><CardTitle>Orçamentos recentes</CardTitle><Link href="/representante/orcamentos" className="text-sm font-semibold text-primary">Ver todos</Link></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Número</TableHead><TableHead>Status</TableHead><TableHead>Total</TableHead></TableRow></TableHeader><TableBody>{quotes.map(q=><TableRow key={q.id}><TableCell><strong>{q.number}</strong><div className="text-xs text-muted-foreground">{dateBR(q.createdAt)}</div></TableCell><TableCell><StatusBadge status={q.status}/></TableCell><TableCell className="font-semibold">{money(q.total)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div></>}
