import { Download, FileText } from "lucide-react"
import { DocumentUploadForm } from "@/components/admin/document-upload-form"
import { PageHeader } from "@/components/page-header"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { requireRole } from "@/lib/auth"
import { dateBR } from "@/lib/format"
import { prisma } from "@/lib/prisma"

export const dynamic = "force-dynamic"

export default async function DocumentsAdmin(){await requireRole(["ADMIN"]);const[products,customers,pdocs,cdocs]=await Promise.all([prisma.product.findMany({select:{id:true,name:true,sku:true},orderBy:{name:"asc"}}),prisma.customer.findMany({select:{id:true,tradeName:true,legalName:true},orderBy:{legalName:"asc"}}),prisma.productDocument.findMany({include:{product:true},orderBy:{createdAt:"desc"},take:30}),prisma.customerDocument.findMany({include:{customer:true},orderBy:{createdAt:"desc"},take:30})]);return <><PageHeader eyebrow="Arquivos" title="Central de documentos" description="Anexe fichas, certificados e arquivos de catálogo ou documentos privados de clientes."/><div className="grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><Card><CardHeader><CardTitle>Novo documento</CardTitle></CardHeader><CardContent><DocumentUploadForm products={products} customers={customers.map(c=>({id:c.id,name:c.tradeName||c.legalName}))}/></CardContent></Card><div className="space-y-6"><Card><CardHeader><CardTitle>Documentos de produtos</CardTitle></CardHeader><CardContent className="space-y-2">{pdocs.map(d=><a key={d.id} href={d.url} target="_blank" className="flex items-center gap-3 rounded-lg border p-3 hover:border-primary/40"><FileText className="size-4 text-primary"/><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{d.title}</strong><span className="text-xs text-muted-foreground">{d.product.sku} • {d.type} • {dateBR(d.createdAt)}</span></span><Download className="size-4 text-muted-foreground"/></a>)}</CardContent></Card><Card><CardHeader><CardTitle>Documentos de clientes</CardTitle></CardHeader><CardContent className="space-y-2">{cdocs.map(d=><a key={d.id} href={d.url} target="_blank" className="flex items-center gap-3 rounded-lg border p-3 hover:border-primary/40"><FileText className="size-4 text-primary"/><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{d.title}</strong><span className="text-xs text-muted-foreground">{d.customer.tradeName||d.customer.legalName} • {d.type}</span></span><Download className="size-4 text-muted-foreground"/></a>)}</CardContent></Card></div></div></>}
